module SchemaProfiler
    USAGE_REQUIRED = "Required"
    USAGE_SUGGESTED = "Suggested"
    USAGE_OPTIONAL = "Optional"
    USAGE_PROHIBITED = "Prohibited"
    USAGES = [USAGE_REQUIRED, USAGE_SUGGESTED, USAGE_OPTIONAL, USAGE_PROHIBITED]
end
